//
// Module my_project_lib.Timer_tb.struct
//
// Created:
//          by - koval.UNKNOWN (COMPUTER-55078E)
//          at - 20:36:26 21.03.2014
//
// Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
//

`resetall
`timescale 1ns/10ps
module Timer_tb;


// Internal Declarations



// Local declarations

// Internal signal declarations
wire       alarm;
wire       clk;
wire [9:0] d;
wire [3:0] high;
wire [3:0] low;
wire       reset;
wire       start;
wire       stop;


// Instances 
Timer U_0( 
   .clk   (clk), 
   .d     (d), 
   .reset (reset), 
   .start (start), 
   .stop  (stop), 
   .alarm (alarm), 
   .high  (high), 
   .low   (low)
); 

Timer_tester U_1( 
   .alarm (alarm), 
   .high  (high), 
   .low   (low), 
   .clk   (clk), 
   .d     (d), 
   .reset (reset), 
   .start (start), 
   .stop  (stop)
); 


endmodule // Timer_tb

